# Generated by Django 5.1.3 on 2024-11-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("author", models.TextField()),
                ("overview", models.TextField()),
                ("image", models.TextField()),
                ("url", models.TextField()),
            ],
        ),
    ]
