apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: deploy-elearning
spec:
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: eks-app
        image: guanhang0502/myapp:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80